server:
  port: 80
  tomcat:
    uri-encoding: utf-8

spring:
  mvc:
    view:
      prefix:
        classpath: /templates/
      suffix: .html
  application:
    name: spring-boot-mongodb
  data:
      mongodb:
        uri: mongodb+srv://admin:admin@cluster0-bxhh0.mongodb.net/yy
